"use client"

import Image from "next/image"
import type { Message as AIMessage } from "ai"
import { Message } from "./message"
import { Card, CardContent } from "@/components/ui/card"

interface ShareableImageContentProps {
  messages: AIMessage[]
}

export function ShareableImageContent({ messages }: ShareableImageContentProps) {
  return (
    <Card className="w-full max-w-md mx-auto border-2 shadow-lg rounded-xl overflow-hidden bg-white dark:bg-gray-950">
      <CardContent className="p-4 space-y-4">
        <div className="flex justify-center mb-4">
          <Image
            src="/images/overthinkr-logo.png"
            alt="Overthinkr Logo"
            width={150}
            height={38}
            className="dark:invert"
          />
        </div>
        <div className="space-y-4">
          {messages.map((m) => (
            <Message key={m.id} content={m.content} role={m.role as "user" | "assistant"} isShareableImage />
          ))}
        </div>
        <div className="text-center text-xs text-muted-foreground mt-4">Generated by Overthinkr.vercel.app</div>
      </CardContent>
    </Card>
  )
}
